version: "3"
services:
  backend:
    container_name: backend
    restart: always
    build: ./backend
    ports:
      - "8181:8181"
    depends_on:
      - test

  test:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: ijn1234
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./mysql-service/data:/var/lib/mysql
      - ./mysql-service/setup.sql:/docker-entrypoint-initdb.d/setup.sql
volumes:
  mysql-service:


